name: 'Publish GitHub Action'
description: 'Publish your GitHub Action'
author: 'TG908'
branding:
  icon: 'truck'
  color: 'blue'
inputs:
  github_token:
    description: 'Token for the github API'
    required: true
  check_tag:
    description: 'when version tag exists then do nothing'
    required: false
    default: false
runs:
  using: 'node12'
  main: 'lib/main.js'
